import type { ToolSeo } from "./types";

const SERVER_NOTE = "The file is converted on our server and deleted as soon as the PDF is ready.";

export const CONVERT_TO: Record<string, ToolSeo> = {
  "jpg-to-pdf": {
    title: "JPG to PDF Converter – Combine Images into One PDF Free",
    description: "Turn JPG, PNG and WEBP images into a PDF. Put several photos in one file, choose A4, Letter or image size, orientation and margins. Free, in your browser.",
    intent: ["jpg to pdf", "image to pdf", "convert jpg to pdf", "png to pdf", "photos to pdf", "combine images into pdf"],
    anchor: "Convert JPG images to PDF",
    howTo: "convert JPG to PDF",
    intro: "Combine photos, screenshots and scanned pages into one PDF in the order you choose, with each image on its own page.",
    steps: [
      "Choose or drop your JPG, PNG or WEBP images.",
      "Use the arrows to put them in order.",
      "Pick the page size (same as image, A4 or Letter), orientation and margin.",
      "Press Convert to PDF and download.",
    ],
    features: ["Many images into one PDF, in your order.", "A4, Letter or each page the size of its image.", "Auto, portrait or landscape pages, with optional margins.", "Images are placed at full quality and never uploaded."],
    uses: ["Send photographed documents as a single PDF.", "Turn receipts into one expense PDF.", "Combine screenshots into a report."],
    limits: ["Large photos make large PDFs; run Compress PDF afterwards if the file is too big to send."],
    faq: [["How do I put multiple JPGs into one PDF?", "Add all the images at once (or use Add more files), arrange them with the arrows, and convert. Each image becomes one page of the same PDF."]],
    related: ["scan-to-pdf", "compress-pdf", "pdf-to-jpg", "compress-image", "merge-pdf"],
  },
  "scan-to-pdf": {
    title: "Scan to PDF with Your Phone Camera – Free Online Scanner",
    description: "Use your phone or laptop camera to scan paper documents into a clean, multi-page PDF. No app to install, and the photos never leave your device.",
    intent: ["scan to pdf", "scan document with phone", "online document scanner", "camera to pdf", "scan pages to pdf"],
    anchor: "Scan paper to PDF with your camera",
    howTo: "scan a document to PDF",
    intro: "Photograph each page with your camera, and the scanner turns the shots into a tidy PDF you can save or share. Works in the browser on phones and computers.",
    steps: ["Allow camera access when asked (or choose existing photos).", "Hold the page flat and press the shutter for each page.", "Check the thumbnails and remove any bad shots.", "Press the build button and download your PDF."],
    features: ["Multi-page scanning in one session.", "Works with the back camera on phones.", "No app and no upload: pictures stay on your device."],
    uses: ["Scan a signed form to send back by email.", "Digitise receipts and notes."],
    limits: ["Good, even light gives the best result. The PDF contains images; run OCR PDF to make the text searchable."],
    related: ["jpg-to-pdf", "ocr-pdf", "compress-pdf", "thumbmark-maker"],
  },
  "word-to-pdf": {
    title: "Word to PDF Converter – Convert DOC & DOCX to PDF Free",
    description: "Convert Word documents (.docx, .doc, .odt, .rtf) to PDF with fonts, tables and images laid out as in Word. Free, several files at once, no sign-up.",
    intent: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf", "word to pdf converter free"],
    anchor: "Convert Word to PDF",
    howTo: "convert Word to PDF",
    intro: `Turn Word documents into PDFs that look the same on every device and can't be accidentally edited. ${SERVER_NOTE}`,
    steps: ["Choose one or more .docx, .doc, .odt or .rtf files.", "Press Convert to PDF.", "Download the PDF (or a ZIP for several files)."],
    features: ["Converts DOCX, DOC, ODT and RTF.", "Keeps page layout, tables, images, headers and footers.", "Batch conversion of several documents."],
    uses: ["Send a CV or cover letter that looks the same for every recruiter.", "Submit assignments and reports in PDF format."],
    limits: ["Fonts that aren't embedded in the document may be replaced with similar ones."],
    related: ["pdf-to-word", "word-editor", "compress-pdf", "merge-pdf"],
  },
  "powerpoint-to-pdf": {
    title: "PowerPoint to PDF – Convert PPT & PPTX Slides to PDF",
    description: "Convert PowerPoint presentations (.pptx, .ppt, .odp) to PDF, one slide per page, for sharing, printing and uploading. Free, no sign-up.",
    intent: ["powerpoint to pdf", "ppt to pdf", "pptx to pdf", "convert slides to pdf"],
    anchor: "Convert PowerPoint to PDF",
    howTo: "convert PowerPoint to PDF",
    intro: `Turn a slide deck into a PDF anyone can open, with every slide as a page. ${SERVER_NOTE}`,
    steps: ["Choose one or more .pptx, .ppt or .odp files.", "Press Convert to PDF.", "Download the PDF."],
    features: ["One slide per page, at slide size.", "Converts PPTX, PPT and ODP.", "Batch conversion."],
    uses: ["Share lecture or pitch slides as a PDF handout.", "Upload slides where only PDF is accepted."],
    limits: ["Animations, transitions and embedded videos don't carry over to PDF."],
    related: ["pdf-to-powerpoint", "powerpoint-editor", "pages-per-sheet", "compress-pdf"],
  },
  "excel-to-pdf": {
    title: "Excel to PDF Converter – Convert XLS, XLSX & CSV to PDF",
    description: "Convert Excel spreadsheets (.xlsx, .xls, .ods, .csv) to PDF, with every sheet on its own pages. Free online Excel to PDF converter, no sign-up.",
    intent: ["excel to pdf", "xlsx to pdf", "convert excel to pdf", "xls to pdf", "spreadsheet to pdf"],
    anchor: "Convert Excel to PDF",
    howTo: "convert Excel to PDF",
    intro: `Turn spreadsheets into PDFs for invoices, reports and records that shouldn't be edited. ${SERVER_NOTE}`,
    steps: ["Choose one or more .xlsx, .xls, .ods or .csv files.", "Press Convert to PDF.", "Download the PDF."],
    features: ["Converts every sheet in the workbook.", "Uses the print area and page setup saved in the file.", "Batch conversion."],
    uses: ["Send an invoice or quotation made in Excel.", "Archive monthly reports as PDF."],
    limits: ["Very wide sheets are split across pages the way Excel prints them; set the page setup in the file, or use CSV to PDF for simple tables."],
    related: ["pdf-to-excel", "excel-editor", "csv-to-pdf"],
  },
  "html-to-pdf": {
    title: "HTML to PDF – Save Any Web Page as a PDF Online",
    description: "Turn a web page into a PDF from its address. Choose A4 or Letter and portrait or landscape. Free online HTML to PDF converter.",
    intent: ["html to pdf", "web page to pdf", "url to pdf", "save website as pdf", "convert webpage to pdf"],
    anchor: "Save a web page as PDF",
    howTo: "save a web page as PDF",
    intro: "Paste a link and get the page as a PDF, rendered by a real browser engine so it looks like the live page.",
    steps: ["Paste the full web address, starting with https://.", "Pick A4 or Letter, and landscape if the page is wide.", "Press Convert to PDF and download."],
    features: ["Real browser rendering, including CSS and images.", "A4 or Letter, portrait or landscape."],
    uses: ["Keep a copy of an article, receipt or booking confirmation.", "Archive a web page as it looked on a given day."],
    limits: ["Only public pages can be converted; pages behind a login or paywall can't be reached.", "Our server fetches the page and deletes the PDF straight after."],
    related: ["markdown-to-pdf", "ebook-to-pdf", "compress-pdf"],
  },
  "markdown-to-pdf": {
    title: "Markdown to PDF Converter – Headings, Tables & Code Blocks",
    description: "Convert Markdown (.md) files to clean, readable PDFs with headings, lists, tables and code blocks. Portrait or landscape. Free online.",
    intent: ["markdown to pdf", "md to pdf", "convert markdown to pdf", "readme to pdf"],
    anchor: "Convert Markdown to PDF",
    howTo: "convert Markdown to PDF",
    intro: `Turn README files, notes and documentation written in Markdown into tidy, typeset PDFs. ${SERVER_NOTE}`,
    steps: ["Choose one or more .md, .markdown or .txt files.", "Turn on Landscape for wide tables if needed.", "Press Convert to PDF and download."],
    features: ["Headings, lists, tables, quotes and code blocks.", "Clean typography for print.", "Batch conversion."],
    uses: ["Share project documentation with people who don't use Markdown.", "Print notes written in Obsidian or a code editor."],
    related: ["pdf-to-markdown", "html-to-pdf", "text-to-handwriting"],
  },
  "csv-to-pdf": {
    title: "CSV to PDF – Turn a CSV File into a Printable Table",
    description: "Convert CSV and TSV files into neat PDF tables with the header row repeated on every page. Portrait or landscape. Free online CSV to PDF converter.",
    intent: ["csv to pdf", "convert csv to pdf", "csv to printable table", "tsv to pdf"],
    anchor: "Convert CSV to a PDF table",
    howTo: "convert CSV to PDF",
    intro: `Exports from banks, shops and databases often come as CSV. This turns them into a readable, printable table. ${SERVER_NOTE}`,
    steps: ["Choose one or more .csv or .tsv files.", "Keep “First row is a header” on to repeat it on every page; turn on Landscape for many columns.", "Press Convert to PDF and download."],
    features: ["Header row repeated on each page.", "Landscape option for wide data.", "Handles comma- and tab-separated files."],
    uses: ["Print a transaction export from your bank.", "Share a contact or inventory list as a PDF."],
    related: ["pdf-to-csv", "excel-to-pdf", "excel-editor"],
  },
  "ebook-to-pdf": {
    title: "EPUB to PDF Converter – Convert eBooks, TXT & HTML to PDF",
    description: "Convert EPUB eBooks, plain text and HTML files into typeset PDFs that are easy to print and read on any device. Free online eBook to PDF converter.",
    intent: ["epub to pdf", "ebook to pdf", "convert epub to pdf", "txt to pdf"],
    anchor: "Convert EPUB to PDF",
    howTo: "convert an eBook to PDF",
    intro: `Turn reflowable eBooks and text files into fixed-layout PDFs for printing or reading where EPUB isn't supported. ${SERVER_NOTE}`,
    steps: ["Choose one or more .epub, .txt or .html files.", "Press Convert to PDF.", "Download the PDF."],
    features: ["Chapters, headings and images from EPUB files.", "Plain text and HTML typeset as readable pages."],
    uses: ["Print an eBook chapter.", "Read an EPUB on a device that only opens PDFs."],
    limits: ["DRM-protected eBooks can't be converted."],
    related: ["pdf-to-epub", "markdown-to-pdf", "html-to-pdf"],
  },
};

export const CONVERT_FROM: Record<string, ToolSeo> = {
  "pdf-to-jpg": {
    title: "PDF to JPG Converter – Convert PDF Pages to Images Free",
    description: "Turn every PDF page into a JPG or PNG image at screen, standard or print quality, or pull out the photos inside. Free, and it runs in your browser.",
    intent: ["pdf to jpg", "pdf to image", "convert pdf to jpg", "pdf to png", "save pdf page as image"],
    anchor: "Convert PDF pages to JPG",
    howTo: "convert PDF to JPG",
    intro: "Save PDF pages as pictures for slides, social posts and messages, or extract the original images embedded in the file.",
    steps: [
      "Choose a PDF.",
      "Pick Page to image, or Extract images to get the photos inside unchanged.",
      "For pages, choose JPG or PNG, a quality (Screen, Standard or Print) and which pages.",
      "Press Convert to images; several images download as a ZIP.",
    ],
    features: ["JPG or PNG output.", "96, 150 or 300 DPI quality.", "Convert all pages or a range.", "Extract embedded images at original quality."],
    uses: ["Post a page of a PDF on social media.", "Insert a PDF page into a presentation or document as an image.", "Get the photos out of a brochure."],
    related: ["jpg-to-pdf", "extract-images", "compress-image", "pdf-to-powerpoint"],
  },
  "pdf-to-word": {
    title: "PDF to Word Converter – Convert PDF to Editable DOCX Free",
    description: "Convert PDF to an editable Word document (.docx) with headings, lists, paragraphs and tables. Free online PDF to Word converter, no sign-up, nothing uploaded.",
    intent: ["pdf to word", "convert pdf to word", "pdf to docx", "pdf to word converter free", "edit pdf in word"],
    anchor: "Convert PDF to Word",
    howTo: "convert PDF to Word",
    intro: "Get an editable .docx back from a PDF. The converter rebuilds the document's structure, with real headings, paragraphs, lists and tables, instead of a page of floating text boxes.",
    steps: ["Choose a PDF with selectable text.", "Press Convert to Word.", "Open the .docx in Word, Google Docs, LibreOffice or our Word editor."],
    features: ["Headings, paragraphs, bullet and numbered lists, and tables.", "Text flows normally, so editing doesn't break the layout.", "Runs on your device; the PDF is never uploaded."],
    uses: ["Update an old CV or contract when you only have the PDF.", "Reuse text and tables from a report."],
    limits: ["Scanned PDFs have no text to convert; run OCR PDF first.", "Complex magazine-style layouts are simplified into a single flow of text."],
    faq: [["Can I edit the converted file in Google Docs?", "Yes. The result is a standard .docx file that Microsoft Word, Google Docs, LibreOffice and our Word editor can open."]],
    related: ["word-to-pdf", "ocr-pdf", "word-editor", "edit-pdf", "pdf-to-excel"],
  },
  "pdf-to-powerpoint": {
    title: "PDF to PowerPoint – Convert PDF to PPTX Slides",
    description: "Convert a PDF into a PowerPoint presentation with one slide per page and the page text in the speaker notes. Free, in your browser.",
    intent: ["pdf to powerpoint", "pdf to ppt", "pdf to pptx", "convert pdf to slides"],
    anchor: "Convert PDF to PowerPoint",
    howTo: "convert PDF to PowerPoint",
    intro: "Turns each page into a slide showing the page as a crisp image, with the page's text copied into the notes so you can reuse it.",
    steps: ["Choose a PDF.", "Press Convert to PowerPoint.", "Open the .pptx in PowerPoint, Google Slides, Keynote or our PowerPoint editor."],
    features: ["One slide per page.", "Page text in the speaker notes.", "Opens in every presentation app."],
    uses: ["Present a PDF report in a meeting.", "Add your own slides around pages from a PDF."],
    limits: ["Pages are images on the slides, so the slide text itself isn't editable; use the notes or PDF to Word to reuse the words."],
    related: ["powerpoint-to-pdf", "powerpoint-editor", "pdf-to-jpg"],
  },
  "pdf-to-excel": {
    title: "PDF to Excel Converter – Extract Tables to XLSX Free",
    description: "Pull tables and columns from a PDF into an Excel spreadsheet (.xlsx), one sheet per page. Free online PDF to Excel converter that runs in your browser.",
    intent: ["pdf to excel", "pdf to xlsx", "convert pdf table to excel", "extract table from pdf", "bank statement pdf to excel"],
    anchor: "Convert PDF tables to Excel",
    howTo: "convert PDF to Excel",
    intro: "Detects the rows and columns of tables in a PDF and puts them into spreadsheet cells, so you can sort, filter and calculate.",
    steps: ["Choose a PDF with selectable text.", "Press Convert to Excel.", "Open the .xlsx in Excel, Google Sheets or our Excel editor and check the columns."],
    features: ["Rows and columns rebuilt from text positions.", "One worksheet per page.", "Numbers stay as text you can convert to values in Excel."],
    uses: ["Analyse a bank or credit card statement.", "Reuse price lists and tables from reports."],
    limits: ["Scanned PDFs need OCR PDF first.", "Tables without clear columns may need tidying after conversion."],
    related: ["pdf-to-csv", "excel-to-pdf", "excel-editor", "ocr-pdf"],
  },
  "pdf-to-markdown": {
    title: "PDF to Markdown Converter – Clean MD from Any PDF",
    description: "Convert PDF to clean Markdown with headings, lists and tables, ready for notes apps, documentation and AI tools. Free and private, in your browser.",
    intent: ["pdf to markdown", "pdf to md", "convert pdf to markdown"],
    anchor: "Convert PDF to Markdown",
    howTo: "convert PDF to Markdown",
    intro: "Extracts the text of a PDF as structured Markdown, so you can paste it into Notion, Obsidian, GitHub or an AI chat with its headings and tables intact.",
    steps: ["Choose a PDF.", "Optionally separate pages with ---.", "Press Convert to Markdown, then copy the text or download the .md file."],
    features: ["Headings, lists and tables as Markdown.", "Preview on the page with copy and download buttons."],
    uses: ["Move PDF documentation into a wiki.", "Prepare a document for an AI assistant."],
    limits: ["Scanned PDFs need OCR PDF first."],
    related: ["markdown-to-pdf", "extract-text", "pdf-to-html"],
  },
  "pdf-to-pdfa": {
    title: "PDF to PDF/A – Archive-Grade PDF (Coming Soon)",
    description: "PDF to PDF/A conversion for long-term archiving is on the Fusion Office roadmap.",
    intent: ["pdf to pdf/a", "pdf/a converter"],
    anchor: "PDF to PDF/A",
    intro: "PDF/A is the archival version of PDF required by many courts and registries. This converter needs a new processing engine and isn't available yet.",
    steps: [],
    features: [],
    uses: [],
    related: ["compress-pdf", "flatten-pdf", "edit-metadata"],
  },
  "pdf-to-html": {
    title: "PDF to HTML Converter – Turn a PDF into a Web Page",
    description: "Convert a PDF into a clean, responsive HTML page with its headings, lists and tables, ready to publish or edit. Free, in your browser.",
    intent: ["pdf to html", "convert pdf to html", "pdf to web page"],
    anchor: "Convert PDF to HTML",
    howTo: "convert PDF to HTML",
    intro: "Produces a single, readable HTML file that reflows on phones, instead of a fixed page layout.",
    steps: ["Choose a PDF.", "Press Convert to HTML.", "Download the .html file and open it in any browser or editor."],
    features: ["Semantic headings, lists and tables.", "Responsive page that works on mobile."],
    uses: ["Publish a PDF's content on a website.", "Make a document readable on small screens."],
    limits: ["Exact visual layout isn't reproduced; the goal is clean, readable HTML."],
    related: ["pdf-to-markdown", "html-to-pdf", "pdf-to-epub"],
  },
  "pdf-to-epub": {
    title: "PDF to EPUB Converter – Make a Reflowable eBook",
    description: "Convert a PDF into an EPUB eBook that reflows on Kindle, Kobo, Apple Books and phone readers. Add an author name. Free, in your browser.",
    intent: ["pdf to epub", "convert pdf to epub", "pdf to ebook", "pdf to kindle"],
    anchor: "Convert PDF to EPUB",
    howTo: "convert PDF to EPUB",
    intro: "Small screens make fixed PDF pages hard to read. EPUB text reflows to fit any screen and font size.",
    steps: ["Choose a PDF.", "Optionally enter the author's name.", "Press Convert to EPUB and download."],
    features: ["Reflowable text with headings preserved.", "Works with Kindle (via Send to Kindle), Kobo and Apple Books."],
    uses: ["Read papers and reports comfortably on an e-reader."],
    limits: ["Scanned PDFs need OCR PDF first; complex layouts are simplified."],
    related: ["ebook-to-pdf", "pdf-to-html", "invert-colours"],
  },
  "pdf-to-csv": {
    title: "PDF to CSV – Extract Tables from PDF to CSV",
    description: "Pull tables and columns out of a PDF into CSV files, all pages in one file or one per page. Free online PDF to CSV converter that runs in your browser.",
    intent: ["pdf to csv", "convert pdf to csv", "extract pdf table to csv"],
    anchor: "Extract PDF tables to CSV",
    howTo: "convert PDF to CSV",
    intro: "CSV opens in every spreadsheet and database tool. This extracts the rows and columns of a PDF's tables as plain comma-separated data.",
    steps: ["Choose a PDF with selectable text.", "Choose one CSV for all pages, or one per page.", "Press Convert to CSV and download."],
    features: ["Rows and columns detected from text positions.", "One combined file or one file per page."],
    uses: ["Import a statement into accounting software.", "Load PDF data into a database or script."],
    limits: ["Scanned PDFs need OCR PDF first."],
    related: ["pdf-to-excel", "csv-to-pdf", "ocr-pdf"],
  },
  "extract-text": {
    title: "Extract Text from PDF – Save PDF Text as TXT",
    description: "Get all the text from a PDF as a plain .txt file, page by page, to copy, search or reuse. Free and private, in your browser.",
    intent: ["extract text from pdf", "pdf to text", "pdf to txt", "copy text from pdf"],
    anchor: "Extract all text from a PDF",
    howTo: "extract text from a PDF",
    intro: "Copies every word in the PDF into a plain text file, in reading order, with no formatting.",
    steps: ["Choose a PDF.", "Press Extract text.", "Copy the text from the preview or download the .txt file."],
    features: ["Plain text in reading order.", "Copy button and .txt download."],
    uses: ["Paste a document's text into another app.", "Search or count words in a long PDF."],
    limits: ["Scanned pages have no text; run OCR PDF first."],
    related: ["pdf-to-word", "pdf-to-markdown", "ocr-pdf"],
  },
  "extract-images": {
    title: "Extract Images from PDF – Save Photos at Original Quality",
    description: "Pull the photos and graphics out of a PDF at their original resolution and download them as image files. Free and private, in your browser.",
    intent: ["extract images from pdf", "save images from pdf", "get pictures out of pdf"],
    anchor: "Extract images from a PDF",
    howTo: "extract images from a PDF",
    intro: "Saves the images embedded in a PDF exactly as they are stored, without re-rendering the page or losing quality.",
    steps: ["Choose a PDF.", "Press Extract images.", "Download the images (several come as a ZIP)."],
    features: ["Original resolution, no recompression where possible.", "All images in one ZIP."],
    uses: ["Reuse product photos from a catalogue.", "Recover pictures from a document whose source files are lost."],
    limits: ["Graphics drawn as vectors (charts, logos) aren't images; use PDF to JPG to capture them."],
    related: ["pdf-to-jpg", "extract-text", "compress-image"],
  },
};
