import type { ToolSeo } from "./types";

export const IMAGE: Record<string, ToolSeo> = {
  "image-editor": {
    title: "Free Online Photo Editor – Crop, Adjust, Filters & Text",
    description: "Edit photos in your browser: crop and straighten, adjust exposure, contrast and colour, apply filters, add text, then resize and save as JPG, PNG or WEBP.",
    intent: ["online photo editor", "image editor online free", "edit photo online", "add text to image", "photo filters online"],
    anchor: "Edit a photo online",
    howTo: "edit a photo",
    intro: "A quick photo editor with the essentials: crop, straighten, light and colour adjustments, filters and text, all non-destructive until you save.",
    steps: ["Choose an image.", "Use the Crop, Adjust, Filters and Text tabs to make changes; undo and redo at any time.", "Open Save to pick the size and format.", "Download the edited image."],
    features: [
      "Crop with free or fixed aspect ratios, and straighten.",
      "Exposure, brightness, contrast, highlights, shadows, saturation, warmth, vignette, sharpen and blur.",
      "Filters and text layers with fonts, colours and backgrounds.",
      "Save as JPG, PNG or WEBP at the size you need.",
    ],
    uses: ["Brighten and straighten a product photo.", "Add a caption to an image for social media."],
    related: ["crop-image", "resize-image", "compress-image", "remove-watermark-image", "convert-image"],
  },
  "compress-image": {
    title: "Compress Image Online – Reduce JPG & PNG Size to 50 KB, 100 KB",
    description: "Make JPG, PNG and WEBP images smaller by quality level, or fit them under an exact size like 20 KB, 50 KB or 100 KB for forms. Free, in your browser.",
    intent: ["compress image", "image compressor", "reduce image size", "compress jpeg to 50kb", "compress image to 100kb", "reduce photo size in kb"],
    anchor: "Compress an image",
    howTo: "compress an image",
    intro: "Shrink photos for websites, email and online application forms. Pick a quality level, or type the maximum size the form accepts and get an image that fits.",
    steps: [
      "Choose one or more images.",
      "Compress by Quality (Light, Recommended or Strong) or by File size, entering a limit such as 50 KB.",
      "Keep the format or save as JPG, PNG or WEBP.",
      "Press Compress and download; the result shows the new size of each file.",
    ],
    features: ["Hit an exact target size in KB or MB.", "Three quality levels.", "Convert to WEBP or JPG for extra savings.", "Batch compress many images at once."],
    uses: ["Upload a photo or signature to an exam, job or government form with a KB limit.", "Speed up a website by shrinking images.", "Send photos over email without hitting attachment limits."],
    limits: ["Very small targets (a few KB) need small dimensions, so the image is also scaled down.", "PNG screenshots compress best when saved as WEBP or JPG."],
    faq: [["How do I compress a photo to under 50 KB?", "Choose File size, type 50, and press Compress. The tool lowers quality, and size if necessary, until the image is 50 KB or smaller."]],
    related: ["resize-image", "convert-image", "compress-pdf", "image-editor"],
  },
  "resize-image": {
    title: "Resize Image Online – By Pixels, Percent, cm or KB",
    description: "Resize photos by percentage, exact pixels or print size in cm, mm or inches, with presets for passport photos and social media. Free, in your browser.",
    intent: ["resize image", "image resizer", "resize image to 1080x1080", "passport photo size", "resize image in cm", "change image dimensions"],
    anchor: "Resize an image",
    howTo: "resize an image",
    intro: "Change an image's dimensions for a website, social post or printed form. Choose pixels, a percentage, or a print size at a given DPI, and optionally cap the file size too.",
    steps: [
      "Choose one or more images.",
      "Resize by Percent, Pixels or Print size, or pick a preset such as Passport photo 3.5 × 4.5 cm or Square 1080.",
      "Keep proportions on, or choose to crop, add borders or stretch to the new shape.",
      "Optionally limit the file size, pick a format, and press Resize.",
    ],
    features: ["Pixels, percent, cm, mm or inches with a DPI setting.", "Presets for passport, signature and stamp sizes, HD and social formats.", "Crop-to-fill, add borders or stretch.", "Optional maximum file size in KB."],
    uses: ["Make a 3.5 × 4.5 cm passport photo for an application.", "Resize to 1080 × 1080 for Instagram.", "Shrink large photos before uploading."],
    related: ["compress-image", "crop-image", "image-editor", "convert-image"],
  },
  "crop-image": {
    title: "Crop Image Online – Square, 16:9, Passport Photo or Free",
    description: "Crop photos to any shape: square, 4:5, 16:9, passport photo or freeform, and rotate or straighten them. Free online image cropper in your browser.",
    intent: ["crop image", "crop image online", "crop photo to square", "crop passport photo", "image cropper"],
    anchor: "Crop an image",
    howTo: "crop an image",
    intro: "Drag a frame over the part of the photo you want to keep, with fixed ratios for common uses or a free crop.",
    steps: ["Choose an image.", "Pick a ratio (free, square, 16:9, passport and more) and drag the frame into place.", "Straighten or rotate if needed.", "Save and download."],
    features: ["Common aspect ratios plus freeform.", "Rotate and straighten while cropping.", "Save as JPG, PNG or WEBP."],
    uses: ["Make a square profile picture.", "Cut a document photo down to just the page."],
    related: ["image-editor", "resize-image", "rotate-image", "crop-pdf"],
  },
  "convert-image": {
    title: "Convert Image Format – HEIC, PNG, JPG & WEBP Converter",
    description: "Convert images to JPG, PNG or WEBP, including iPhone HEIC, GIF, BMP and SVG. Set quality and a background for transparent areas. Free, in your browser.",
    intent: ["heic to jpg", "png to jpg", "jpg to png", "webp to jpg", "image converter", "convert image format"],
    anchor: "Convert images to JPG, PNG or WEBP",
    howTo: "convert an image to another format",
    intro: "Change the format of one or many images: JPG for photos and small files, PNG for sharp graphics and transparency, WEBP for small modern files.",
    steps: ["Choose one or more images (HEIC, PNG, JPG, WEBP, GIF, BMP or SVG).", "Pick JPG, PNG or WEBP.", "Set the quality, and a fill colour for transparent areas when saving as JPG.", "Press Convert and download."],
    features: ["Reads HEIC (where your browser supports it), GIF, BMP, SVG, AVIF and more.", "Quality control for JPG and WEBP.", "Batch conversion."],
    uses: ["Turn iPhone HEIC photos into JPGs that open everywhere.", "Convert PNG screenshots to smaller JPGs or WEBPs.", "Turn a WEBP from a website into a JPG."],
    limits: ["HEIC decoding depends on the browser; Safari supports it, some others don't."],
    related: ["compress-image", "resize-image", "jpg-to-pdf"],
  },
  "remove-watermark-image": {
    title: "Remove Watermark from Photo – Erase Logos & Date Stamps",
    description: "Paint over a watermark, logo, date stamp or small object in a photo and it's filled in from its surroundings. Free, and the image never leaves your device.",
    intent: ["remove watermark from image", "remove object from photo", "remove date stamp from photo", "erase logo from image"],
    anchor: "Remove a watermark from a photo",
    howTo: "remove a watermark from a photo",
    intro: "Brush over what you want gone and the tool fills the area by continuing the textures around it, all on your device.",
    steps: ["Choose an image.", "Brush over the watermark or object; adjust the brush size for detail.", "Press Remove, refine with more passes if needed.", "Download the cleaned image."],
    features: ["Content-aware fill from surrounding pixels.", "Adjustable brush and multiple passes.", "Processing on your device."],
    uses: ["Remove a date stamp from an old photo.", "Clean up a stray object or blemish."],
    limits: ["Works best on small marks over simple backgrounds; large logos on detailed areas may leave traces.", "Only edit images you have the right to change."],
    related: ["image-editor", "remove-watermark", "crop-image"],
  },
  "rotate-image": {
    title: "Rotate Image Online – Turn or Mirror Many Photos at Once",
    description: "Rotate images 90° or 180° and mirror them horizontally or vertically, one or many at a time. Free online image rotator that works in your browser.",
    intent: ["rotate image", "rotate photo online", "flip image", "mirror image online"],
    anchor: "Rotate images",
    howTo: "rotate an image",
    intro: "Fix sideways phone photos and mirrored selfies in a batch, then download them all.",
    steps: ["Choose one or more images.", "Pick 90° right, 180° or 90° left, and mirror if needed.", "Press Rotate and download."],
    features: ["90°, 180° and 270° rotation.", "Horizontal and vertical mirroring.", "Batch processing."],
    uses: ["Fix photos that show sideways on websites.", "Un-mirror selfies with text in them."],
    related: ["crop-image", "image-editor", "rotate-pdf"],
  },
  "thumbmark-maker": {
    title: "Thumbmark Maker – Thumb Impression to Transparent PNG",
    description: "Photograph your thumbprint and get a clean thumb impression on a transparent background, in blue, violet or black ink, for online forms. Free.",
    intent: ["thumb impression online", "thumbprint for form", "thumb impression png", "digital thumb impression"],
    anchor: "Make a digital thumb impression",
    howTo: "make a digital thumb impression",
    intro: "Some online applications ask for an uploaded thumb impression. Press your thumb on an ink pad and paper (or take a clear photo of it), and this turns it into a clean, transparent image.",
    steps: ["Take or choose a photo of your thumbprint on white paper.", "Pick the ink colour and adjust the strength.", "Press Make thumbmark and download the transparent PNG."],
    features: ["Removes the paper background.", "Blue, violet or black ink.", "Adjustable strength for faint prints."],
    uses: ["Upload a left thumb impression to exam and government application forms."],
    limits: ["Check each form's rules: some require a scan of a physical impression rather than a photo."],
    related: ["resize-image", "compress-image", "sign-pdf"],
  },
};

export const OFFICE: Record<string, ToolSeo> = {
  "word-editor": {
    title: "Online Word Editor – Edit DOCX Files Free in Your Browser",
    description: "Open and edit Word documents (.docx, .doc, .odt, .rtf) online: fonts, headings, lists, tables and images. Save as Word or PDF. Free, no install.",
    intent: ["online word editor", "edit docx online", "edit word document online free", "docx editor", "word online free"],
    anchor: "Edit a Word document online",
    howTo: "edit a Word document online",
    intro: "A word processor in your browser for everyday documents. Open a .docx, edit it with familiar formatting tools, and download it as Word or PDF.",
    steps: ["Open a Word file, or start from Blank or a template.", "Edit text, styles, lists, tables and images with the toolbar.", "Your draft saves on this device as you type.", "Download as .docx, PDF or HTML."],
    features: ["Headings, fonts, colours, alignment, lists and tables.", "Images with resizing, page breaks and page setup.", "Find and replace, print, word count.", "Templates to start from."],
    uses: ["Edit a CV or letter on a computer without Word.", "Make quick changes to a document someone emailed you."],
    limits: ["Advanced Word features such as tracked changes, macros and complex text boxes aren't supported.", "Old .doc, .odt and .rtf files are converted on our server when opened."],
    related: ["word-to-pdf", "pdf-to-word", "excel-editor", "powerpoint-editor"],
  },
  "excel-editor": {
    title: "Online Excel Editor – Edit XLSX & CSV Spreadsheets Free",
    description: "Open and edit Excel spreadsheets (.xlsx, .xls, .ods, .csv) online with formulas, formatting, sorting and several sheets. Save as Excel, PDF or CSV. Free.",
    intent: ["online excel editor", "edit xlsx online", "spreadsheet online free", "edit csv online", "excel online free"],
    anchor: "Edit a spreadsheet online",
    howTo: "edit a spreadsheet online",
    intro: "A spreadsheet editor in your browser. Open an Excel or CSV file, work with formulas, formatting and multiple sheets, and save it back as .xlsx, PDF or CSV.",
    steps: ["Open a spreadsheet, or start from Blank, Monthly budget or Invoice.", "Type values and formulas, format cells, sort, and freeze rows or columns.", "Add or rename sheets at the bottom.", "Download as .xlsx, PDF or CSV."],
    features: ["Hundreds of Excel-compatible formulas.", "Cell formatting, number formats, sorting and freezing.", "Multiple sheets, copy and paste with Excel and Google Sheets.", "Templates for budgets and invoices."],
    uses: ["Edit a budget or price list without Excel.", "Clean up a CSV export before importing it elsewhere."],
    limits: ["Charts, pivot tables and macros aren't supported.", "Old .xls and .ods files are converted on our server when opened."],
    related: ["excel-to-pdf", "pdf-to-excel", "csv-to-pdf", "word-editor"],
  },
  "powerpoint-editor": {
    title: "Online PowerPoint Editor – Edit PPTX Slides Free",
    description: "Open and edit PowerPoint presentations (.pptx, .ppt, .odp) online: text, shapes, pictures, tables and notes. Present full-screen or save as PPTX or PDF. Free.",
    intent: ["online powerpoint editor", "edit pptx online", "presentation maker online free", "powerpoint online free"],
    anchor: "Edit a presentation online",
    howTo: "edit a presentation online",
    intro: "Open a slide deck in your browser, edit text, shapes, images and tables, add speaker notes, and present it full-screen or download it as PowerPoint or PDF.",
    steps: ["Open a .pptx, or start from Blank or a theme.", "Add slides, text, shapes, images and tables; drag to move and resize.", "Write speaker notes under each slide.", "Present full-screen, or download as .pptx or PDF."],
    features: ["Text, shapes, images, lines and tables with formatting.", "Slide sorter, layouts, themes and backgrounds.", "Speaker notes and full-screen presenting."],
    uses: ["Make last-minute changes to a deck on any computer.", "Build a simple presentation from a theme."],
    limits: ["Animations, transitions, SmartArt and embedded media aren't supported.", "Old .ppt and .odp files are converted on our server when opened."],
    related: ["powerpoint-to-pdf", "pdf-to-powerpoint", "word-editor", "excel-editor"],
  },
};
