import type { ToolSeo } from "./types";

export const OPTIMIZE: Record<string, ToolSeo> = {
  "compress-pdf": {
    title: "Compress PDF Online Free – Reduce PDF File Size",
    description: "Make PDF files smaller while text stays sharp and selectable. Choose less, recommended or extreme compression. Free, no sign-up, and nothing is uploaded.",
    intent: ["compress pdf", "compress pdf online", "reduce pdf size", "make pdf smaller", "pdf compressor", "compress pdf free"],
    anchor: "Compress your PDF",
    howTo: "compress a PDF",
    intro: "Shrink PDFs for email, WhatsApp and upload portals. Images inside the file are re-encoded at a sensible resolution, while the text stays real text, so it remains sharp and searchable.",
    steps: [
      "Choose one or more PDF files.",
      "Pick a level: Less (best quality), Recommended, or Extreme (smallest file).",
      "Optionally turn images grayscale or remove hidden metadata to save a little more.",
      "Press Compress PDF and download; the result shows how much smaller each file got.",
    ],
    features: [
      "Three compression levels to trade size against image quality.",
      "Text and vector graphics are kept, so compressed PDFs stay searchable.",
      "Optional grayscale images and metadata removal.",
      "Compress several PDFs at once.",
    ],
    uses: [
      "Get a scan under an email attachment limit.",
      "Meet upload limits on job, visa, university or tax portals.",
      "Save storage space for archived statements and reports.",
    ],
    limits: [
      "Savings come mostly from images. A PDF that is mostly text is already small and may shrink only a little.",
      "If the file must fit a strict limit and still doesn't, Split by size can break it into parts.",
    ],
    faq: [
      ["How much smaller will my PDF get?", "It depends on what's inside. Scans and photo-heavy PDFs often shrink by 50–90%. Text-only PDFs are usually already compact."],
      ["Does compressing a PDF lower the quality?", "Only images are affected. Recommended keeps photos clear on screen and in print; Extreme makes them visibly softer in exchange for the smallest file."],
    ],
    related: ["split-by-size", "gst-filing-prep", "compress-image", "pdf-to-zip", "repair-pdf"],
  },
  "repair-pdf": {
    title: "Repair PDF – Fix Damaged or Corrupted PDF Files Online",
    description: "Recover the pages of a PDF that won't open, is truncated or has a broken structure, and save a clean copy. Free online PDF repair that runs in your browser.",
    intent: ["repair pdf", "fix corrupted pdf", "pdf won't open", "recover damaged pdf", "repair pdf online"],
    anchor: "Repair a damaged PDF",
    howTo: "repair a PDF",
    intro: "Rebuilds a damaged PDF from whatever can still be read: broken cross-reference tables, cut-off downloads and files other tools refuse to open.",
    steps: ["Choose the damaged PDF.", "Press Repair PDF.", "Download the rebuilt file and check that the pages you need are there."],
    features: ["Rebuilds the file structure from readable objects.", "Recovers every page that can still be decoded.", "Works on several files at once."],
    uses: ["Open an attachment that was cut off while downloading.", "Rescue a PDF other tools reject with “file is damaged”."],
    limits: ["Pages whose content is missing from the file can't be recreated.", "Encrypted PDFs need their password; unlock them first."],
    related: ["compress-pdf", "unlock-pdf", "organize-pdf"],
  },
  "ocr-pdf": {
    title: "OCR PDF Online – Make Scanned PDFs Searchable",
    description: "Add a hidden, selectable text layer to scanned PDFs so you can search, copy and convert them. Free OCR that runs on your device for English text.",
    intent: ["ocr pdf", "make pdf searchable", "scanned pdf to text", "ocr online free", "convert scanned pdf to searchable pdf"],
    anchor: "Make a scanned PDF searchable",
    howTo: "make a scanned PDF searchable",
    intro: "Optical character recognition reads the text in scanned pages and adds it to the PDF as an invisible layer. The pages look the same, but you can now search, select and copy the words.",
    steps: [
      "Choose a scanned PDF.",
      "Keep “Skip pages that already have text” on to save time on mixed documents.",
      "Press Make searchable; the first run downloads the recognition engine.",
      "Download the searchable PDF.",
    ],
    features: ["Text layer is placed exactly over the words on the page.", "Skips pages that already contain text.", "Runs on your device; the scan is never uploaded."],
    uses: [
      "Search inside scanned contracts, letters and receipts.",
      "Prepare a scan for PDF to Word, PDF to Excel or Chat with PDF.",
      "Copy a paragraph from a photographed page.",
    ],
    limits: ["Recognition is tuned for English text.", "Handwriting and very low-resolution or skewed scans give poor results."],
    faq: [["Does OCR change how my PDF looks?", "No. The original page images stay the same; the recognised text sits invisibly on top of them."]],
    related: ["pdf-to-word", "extract-text", "scan-to-pdf", "compress-pdf", "chat-with-pdf"],
  },
  "gst-filing-prep": {
    title: "GST Portal PDF Size Limit – Compress & Split PDFs for GST Upload",
    description: "Prepare PDFs for the GST portal: compress and split replies, SCN responses and appeal documents so each file fits the 2 MB, 5 MB or 10 MB upload limit.",
    intent: ["gst portal pdf size limit", "compress pdf for gst portal", "reduce pdf size to 2mb", "gst reply upload size", "split pdf for gst appeal"],
    anchor: "Prepare a PDF for the GST portal",
    howTo: "prepare a PDF for GST portal upload",
    intro: "GST replies, show cause notice responses and appeal annexures often exceed the portal's per-file limit. This tool compresses the PDF and, if it's still too big, splits it into numbered parts that each fit.",
    steps: ["Choose the PDF you need to upload.", "Pick the portal's limit per file: 2 MB, 5 MB or 10 MB.", "Press Prepare for upload and download the parts, ready to attach in order."],
    features: ["Compression first, splitting only if needed.", "Every part is guaranteed to be under the chosen limit.", "Parts are numbered in page order."],
    uses: ["Upload DRC-06 replies and supporting documents.", "Attach large annexures to GST appeals (APL-01).", "Any portal with a strict per-file size limit."],
    related: ["compress-pdf", "split-by-size", "gst-invoice"],
  },
};

export const EDIT: Record<string, ToolSeo> = {
  "edit-pdf": {
    title: "Edit PDF Online Free – Change Text, Add Images & Annotate",
    description: "A free online PDF editor: change existing text in its original font, add text, images, shapes and drawings, highlight, comment, redact and sign. No sign-up.",
    intent: ["pdf editor online", "edit pdf", "edit pdf online free", "edit text in pdf", "free pdf editor"],
    anchor: "Edit a PDF online",
    howTo: "edit a PDF",
    intro: "A full PDF editor in your browser. Click any line to change the text that's already there, or add text, images, shapes, highlights, comments and signatures, then download the edited PDF.",
    steps: [
      "Open your PDF (or start a blank document).",
      "Pick Edit text and click a line to change it, or use the toolbar to add text, images, shapes and drawings.",
      "Use the page sidebar to reorder, rotate, add or delete pages.",
      "Download the edited PDF; your work is also saved on this device as you go.",
    ],
    features: [
      "Edit existing text: the new words keep the original font, size and colour, and the old ones are removed.",
      "Add text boxes, images, rectangles, ellipses, lines, arrows, pen and marker drawings.",
      "Highlight, underline and strike out text, and add comments that open in any PDF reader.",
      "Redact (permanently remove) or white out content, and sign with a drawn, typed or uploaded signature.",
      "Page tools, layers, search, undo and redo, and keyboard shortcuts.",
    ],
    uses: ["Fix a typo or update a date in a PDF you didn't create.", "Fill in a non-fillable form by typing on it.", "Annotate a draft with highlights and comments for a colleague."],
    limits: ["Scanned pages are images, so their words can't be edited as text; you can still add text on top.", "Works best on a computer; on phones the editor is usable but cramped."],
    faq: [
      ["Can I change the text that's already in a PDF?", "Yes. Choose Edit text and click a line. The replacement uses the original font, size and colour, and the old text is removed from the file rather than covered."],
      ["Is my PDF uploaded to edit it?", "No. The editor runs in your browser. Files are only sent to our server if you choose to save to the cloud."],
    ],
    related: ["sign-pdf", "pdf-forms", "redact-pdf", "organize-pdf", "watermark-pdf"],
  },
  "sign-pdf": {
    title: "Sign PDF Online Free – Add Your Signature to a PDF",
    description: "Sign a PDF with a signature you draw, type or upload, place it anywhere on the page, and download the signed file. Free, no sign-up, and the PDF stays on your device.",
    intent: ["sign pdf", "sign pdf online free", "add signature to pdf", "electronic signature pdf", "esign pdf"],
    anchor: "Sign a PDF",
    howTo: "sign a PDF",
    intro: "Add your signature to contracts, forms and letters without printing them. Draw it, type your name in a handwriting font, or upload a photo of your signature, then place and size it on the page.",
    steps: [
      "Open the PDF in the editor.",
      "Choose Signature and draw, type or upload your signature; tick “remember” to reuse it later.",
      "Click the page to place it, then drag and resize it into position.",
      "Add the date with a text box if needed, and download the signed PDF.",
    ],
    features: ["Draw, type or upload a signature; uploaded images can have their background removed.", "Saved signatures for one-click signing next time.", "Sign as many pages as you need."],
    uses: ["Sign a rental agreement or offer letter.", "Initial every page of a contract.", "Sign school or bank forms received by email."],
    limits: ["This adds a visible signature image (a simple electronic signature). It is not a certificate-based digital signature."],
    faq: [["Is a signature added this way legally valid?", "Simple electronic signatures are accepted for many everyday agreements in most countries, but some documents require a certified digital signature. Check what the recipient accepts."]],
    related: ["edit-pdf", "flatten-pdf", "protect-pdf", "pdf-forms"],
  },
  "watermark-pdf": {
    title: "Add Watermark to PDF – Text or Image Watermark Online",
    description: "Stamp text such as “CONFIDENTIAL” or your logo on PDF pages. Set font, size, colour, transparency, rotation and position, or tile it across the page. Free.",
    intent: ["add watermark to pdf", "watermark pdf", "watermark pdf online free", "add logo to pdf", "confidential stamp pdf"],
    anchor: "Add a watermark to a PDF",
    howTo: "add a watermark to a PDF",
    intro: "Mark documents as drafts, confidential, or yours. Use text or an image, control how strong it looks, and apply it to all pages or a selection.",
    steps: ["Choose one or more PDFs.", "Pick Text or Image, then set the font, size and colour, or the logo width.", "Adjust transparency, rotation and position, or tile it across the page.", "Press Add watermark and download."],
    features: ["Text or image (PNG, JPG) watermarks.", "Transparency, rotation (0°, 45°, 90°) and nine positions.", "Tiled mode covers the whole page.", "Apply to selected pages only."],
    uses: ["Mark drafts and confidential reports.", "Brand proposals and price lists with your logo.", "Discourage reuse of shared ID copies (“For bank KYC only”)."],
    related: ["header-footer", "page-numbers", "remove-watermark", "protect-pdf"],
  },
  "page-numbers": {
    title: "Add Page Numbers to PDF Online – Choose Position & Style",
    description: "Number PDF pages as 1, Page 1, Page 1 of N or 1 / N, in any of nine positions, starting from any number and skipping pages you choose. Free.",
    intent: ["add page numbers to pdf", "number pdf pages", "insert page numbers pdf", "pdf page numbering"],
    anchor: "Add page numbers to a PDF",
    howTo: "add page numbers to a PDF",
    intro: "Insert page numbers into a finished PDF, with control over format, position, starting number, size and which pages are numbered.",
    steps: ["Choose a PDF.", "Pick a format, such as “Page 1 of N”, and a position.", "Set the first number, size, margin and colour, and the pages to number.", "Press Add page numbers and download."],
    features: ["Five number formats including “Page X of Y”.", "Nine positions and three margins.", "Start from any number; number only some pages."],
    uses: ["Number a thesis or report before printing.", "Paginate merged documents for a submission."],
    limits: ["For legal exhibit numbering with prefixes, use Bates numbering."],
    related: ["header-footer", "bates-numbering", "merge-pdf", "watermark-pdf"],
  },
  "remove-watermark": {
    title: "Remove Watermark from PDF – Delete Stamps & Logos for Real",
    description: "Find watermarks, stamps and repeated logos in a PDF and delete them from the file, not just cover them. Pick which marks to remove. Free and in your browser.",
    intent: ["remove watermark from pdf", "delete watermark pdf", "remove stamp from pdf", "pdf watermark remover"],
    anchor: "Remove a watermark from a PDF",
    howTo: "remove a watermark from a PDF",
    intro: "Scans the PDF for text and images that repeat across pages, shows you each candidate, and removes the ones you choose from the page content itself.",
    steps: ["Choose the PDF.", "Review the watermarks and repeated items it finds, with a preview of each.", "Tick the ones to remove and press Remove.", "Check the preview and download the cleaned PDF."],
    features: ["Detects text, image and vector watermarks.", "Removes the objects from the file instead of painting over them.", "Shows a preview before you download."],
    uses: ["Remove a “DRAFT” stamp from your own final document.", "Clean up template logos you're allowed to remove."],
    limits: ["Watermarks that are part of a scanned image can't be separated from the page.", "Only remove marks from documents you have the right to change."],
    related: ["remove-watermark-image", "watermark-pdf", "edit-pdf", "redact-pdf"],
  },
  "crop-pdf": {
    title: "Crop PDF Online – Trim Margins or Keep a Selected Area",
    description: "Trim white margins from PDF pages or crop every page to the area you draw. Apply to all pages or one at a time. Free PDF cropper that runs in your browser.",
    intent: ["crop pdf", "crop pdf online", "trim pdf margins", "remove white margins pdf", "cut pdf page"],
    anchor: "Crop PDF pages",
    howTo: "crop a PDF",
    intro: "Remove wide margins so pages read better on screens, or keep just the part of the page you need.",
    steps: ["Choose a PDF.", "Drag the crop box on the page preview, or pick one of the quick margin presets.", "Choose which pages the crop applies to.", "Save and download the cropped PDF."],
    features: ["Visual crop box on a page preview, plus quick margin presets.", "Apply the crop to all pages or only some.", "Content outside the box is hidden, not deleted, so text stays intact."],
    uses: ["Make academic papers easier to read on a tablet.", "Cut a receipt or ticket out of a full-page scan."],
    limits: ["Cropping hides the area outside the box; to remove sensitive content permanently, use Redact PDF."],
    related: ["split-in-half", "redact-pdf", "organize-pdf"],
  },
  "pdf-forms": {
    title: "Fill PDF Forms Online – Type into Fillable PDFs & Flatten",
    description: "Find the fields in a fillable PDF form, type your answers, tick boxes and choose options, then download it filled in, or flattened so it can't be changed.",
    intent: ["fill pdf form", "fill out pdf online", "fillable pdf", "complete pdf form", "flatten pdf form"],
    anchor: "Fill in a PDF form",
    howTo: "fill in a PDF form",
    intro: "Lists every field in a fillable PDF as a simple form you can complete, including text fields, checkboxes, radio buttons and dropdowns.",
    steps: ["Choose the PDF form.", "Fill in the fields listed on the left.", "Turn on Flatten if the answers should be locked into the page.", "Download the completed form."],
    features: ["Text fields, checkboxes, radio buttons and dropdowns.", "Optional flattening for a final, non-editable copy."],
    uses: ["Complete government and bank application forms.", "Fill in an HR form and send it back as a locked PDF."],
    limits: ["Forms without real fields (a scanned or flat form) have nothing to fill; type on them with the PDF editor instead."],
    related: ["edit-pdf", "flatten-pdf", "sign-pdf"],
  },
  "bates-numbering": {
    title: "Bates Numbering PDF – Add Sequential Bates Stamps Online",
    description: "Stamp sequential Bates numbers with a prefix, suffix and fixed digits on every page, continuing across several PDFs. Free Bates stamping for legal documents.",
    intent: ["bates numbering", "bates stamp pdf", "add bates numbers to pdf", "legal page numbering"],
    anchor: "Add Bates numbers to PDFs",
    howTo: "add Bates numbers to a PDF",
    intro: "Bates numbers give every page in a legal production a unique, sequential ID such as ABC-000123. Numbering continues from one file to the next so the whole set is consistent.",
    steps: ["Choose the PDFs in production order.", "Set the prefix, suffix, starting number and number of digits.", "Choose the position and size.", "Press Add Bates numbers and download."],
    features: ["Prefix, suffix and zero-padded digits.", "Numbering continues across multiple files.", "Any of nine positions on the page."],
    uses: ["Document productions in litigation and discovery.", "Numbering exhibits and audit evidence."],
    related: ["page-numbers", "header-footer", "merge-pdf"],
  },
  "header-footer": {
    title: "Add Header and Footer to PDF – Text, Page Numbers & Dates",
    description: "Add header and footer text to PDF pages, with automatic page numbers, dates and the file name. Set size, margin, colour and a separator line. Free.",
    intent: ["add header to pdf", "add footer to pdf", "pdf header and footer", "insert footer in pdf"],
    anchor: "Add headers and footers to a PDF",
    howTo: "add a header and footer to a PDF",
    intro: "Put a title, company name, date or page number at the top and bottom of every page, aligned left, centre or right.",
    steps: ["Choose the PDF.", "Type the header and footer text in the left, centre and right slots; insert page number, total, date or file name.", "Adjust size, margin and colour, and add a separator line if you like.", "Press Add headers & footers and download."],
    features: ["Six slots: left, centre and right in both header and footer.", "Automatic page number, page count, date and file name.", "Optional thin separator line."],
    uses: ["Add a company name and confidentiality note to reports.", "Put the document title and date on every page of minutes."],
    related: ["page-numbers", "watermark-pdf", "bates-numbering"],
  },
  "flatten-pdf": {
    title: "Flatten PDF Online – Lock Form Fields & Annotations",
    description: "Merge filled form fields, comments, stamps and drawings into the page so they can't be edited, and remove scripts. Free online PDF flattener.",
    intent: ["flatten pdf", "flatten pdf online", "lock pdf form fields", "make pdf non editable"],
    anchor: "Flatten a PDF",
    howTo: "flatten a PDF",
    intro: "Flattening turns interactive parts of a PDF into ordinary page content. Answers can no longer be changed, annotations print reliably, and embedded scripts are removed.",
    steps: ["Choose the PDF.", "Choose what to flatten: form fields, comments and drawings, and whether to remove scripts.", "Press Flatten PDF and download."],
    features: ["Flatten forms, annotations or both.", "Links keep working after flattening.", "Removes JavaScript for safer sharing."],
    uses: ["Send a filled form so the recipient can't alter it.", "Make sure signatures and stamps print exactly as shown."],
    limits: ["Flattening can't be undone in the new file; keep the original if you might edit it again."],
    related: ["pdf-forms", "sign-pdf", "protect-pdf"],
  },
  "edit-metadata": {
    title: "Edit PDF Metadata – Change Title, Author & Keywords",
    description: "View and change a PDF's title, author, subject, keywords, creator and dates, or clear them before sharing. Free PDF properties editor in your browser.",
    intent: ["edit pdf metadata", "change pdf title", "change pdf author", "pdf properties editor", "remove pdf metadata"],
    anchor: "Edit a PDF's title and author",
    howTo: "edit PDF metadata",
    intro: "The document properties of a PDF show up in search results, browser tabs and file managers. Read them, correct them, or remove them.",
    steps: ["Choose the PDF.", "Edit the title, author, subject, keywords, creator, producer or dates.", "Press Save properties and download."],
    features: ["Every standard document property.", "Clear fields you don't want to share."],
    uses: ["Give a PDF a proper title so it doesn't appear as “Untitled” or “Microsoft Word - final_v3”.", "Remove the author name before publishing."],
    related: ["privacy-scanner", "compress-pdf", "protect-pdf"],
  },
  "invert-colours": {
    title: "Invert PDF Colours – Dark Mode, Sepia & Grayscale PDF",
    description: "Make a dark-mode, sepia, grayscale or high-contrast version of any PDF for easier reading at night or on e-readers. Free and private, in your browser.",
    intent: ["invert pdf colors", "dark mode pdf", "pdf to grayscale", "convert pdf to black and white", "sepia pdf"],
    anchor: "Make a dark-mode PDF",
    howTo: "invert the colours of a PDF",
    intro: "Create a copy of a PDF that's easier on the eyes or cheaper to print: dark mode, warm sepia, grayscale or high contrast.",
    steps: ["Choose a PDF.", "Pick a style: Dark mode, Sepia, Grayscale or High contrast.", "Press Change colours and download."],
    features: ["Four reading styles.", "Grayscale also saves colour ink when printing."],
    uses: ["Read long papers at night.", "Print a colour document in black and white."],
    limits: ["Pages are rendered as images in the new copy, so text is no longer selectable; run OCR PDF if you need it."],
    related: ["compress-pdf", "ocr-pdf", "pdf-to-jpg"],
  },
  "text-to-handwriting": {
    title: "Text to Handwriting Converter – Realistic Handwritten Pages",
    description: "Type or paste text and get realistic handwritten pages as a PDF, on lined, squared or plain paper, with blue, black or red ink. Free, no sign-up.",
    intent: ["text to handwriting", "text to handwriting converter", "convert typed text to handwriting", "handwritten assignment generator"],
    anchor: "Turn typed text into handwriting",
    howTo: "convert text to handwriting",
    intro: "Turns typed text into pages that look handwritten, with natural variation in every letter so it doesn't look like a font.",
    steps: ["Type or paste your text.", "Choose a handwriting style, paper (lined, squared or plain) and ink colour.", "Adjust size and the amount of natural wobble.", "Press Write it and download the PDF."],
    features: ["Several handwriting styles.", "Lined, squared and plain paper.", "Blue, black and red ink, adjustable size and messiness."],
    uses: ["Make handwritten-style notes and cards.", "Create practice sheets and mock-ups."],
    related: ["pdf-to-handwriting", "markdown-to-pdf"],
  },
  "pdf-to-handwriting": {
    title: "PDF to Handwriting – Turn PDF Text into Handwritten Notes",
    description: "Convert the text of a PDF into realistic handwritten pages on lined, squared or plain paper, as a downloadable PDF. Free and in your browser.",
    intent: ["pdf to handwriting", "convert pdf to handwritten notes", "pdf text to handwriting"],
    anchor: "Turn a PDF into handwritten notes",
    howTo: "turn a PDF into handwriting",
    intro: "Reads the text of a PDF and writes it out again as handwritten pages, using the same styles, papers and inks as Text to handwriting.",
    steps: ["Choose a PDF with selectable text.", "Pick the handwriting style, paper and ink.", "Press Write it and download."],
    features: ["Keeps paragraphs from the original.", "Same styles and options as Text to handwriting."],
    uses: ["Turn typed study notes into handwritten-looking pages."],
    limits: ["Images, tables and layout aren't reproduced; only the text is written out.", "Scanned PDFs need OCR PDF first."],
    related: ["text-to-handwriting", "extract-text", "ocr-pdf"],
  },
  "gst-invoice": {
    title: "GST Invoice Generator – Create GST Tax Invoices as PDF",
    description: "Create a GST tax invoice with GSTIN checks, HSN/SAC codes, automatic CGST+SGST or IGST and amount in words, then download it as a PDF. Free, no sign-up.",
    intent: ["gst invoice generator", "gst invoice format", "create gst invoice online", "gst bill maker", "tax invoice pdf"],
    anchor: "Create a GST invoice",
    howTo: "create a GST invoice",
    intro: "Fill in your business and customer details and the items sold. The tax split, totals and amount in words are worked out for you, and the next invoice number is ready for next time.",
    steps: [
      "Enter your business details and the customer's; GSTINs are checked as you type.",
      "Add each item with its HSN or SAC code, quantity, rate and GST rate.",
      "Check the totals: CGST and SGST for sales within your state, IGST for sales to another state.",
      "Download the invoice as a PDF.",
    ],
    features: ["GSTIN format validation.", "Intra-state (CGST + SGST) or inter-state (IGST) worked out from the place of supply.", "HSN/SAC codes, discounts and amount in words.", "Your details are remembered on this device for the next invoice."],
    uses: ["Bill customers as a freelancer or small business registered under GST.", "Make a quick invoice without accounting software."],
    limits: ["This creates an invoice document. E-invoicing (IRN and QR code from the IRP) must still be done on the government portal where it applies to you."],
    related: ["gst-filing-prep", "compress-pdf", "sign-pdf"],
  },
};
