import type { ToolSeo } from "./types";

export const ORGANIZE: Record<string, ToolSeo> = {
  "merge-pdf": {
    title: "Merge PDF Online Free – Combine PDF Files in Any Order",
    description: "Combine two or more PDF files into one document in the order you choose. Free, no sign-up, and the files are merged in your browser without uploading.",
    intent: ["merge pdf", "combine pdf files", "merge pdf online free", "join pdf", "combine pdfs into one"],
    anchor: "Merge multiple PDF files",
    howTo: "merge PDF files",
    intro: "Combine several PDFs into a single document. Put the files in the order you want and download one merged PDF, with every page kept exactly as it was.",
    steps: [
      "Choose or drop two or more PDF files.",
      "Use the up and down arrows on each file to set the order; the number on each preview is its position.",
      "Press Merge PDF and download the combined file.",
    ],
    features: [
      "Merge as many PDFs as your device can hold in memory.",
      "Page thumbnails and page counts so you can check each file before merging.",
      "Text, links and image quality are kept: pages are copied, not re-rendered.",
      "Works offline once the page has loaded, because nothing is uploaded.",
    ],
    uses: [
      "Put a job application together: cover letter, CV and certificates in one PDF.",
      "Combine monthly bank statements or invoices into one file for an accountant.",
      "Join scanned pages that were saved as separate PDFs.",
    ],
    limits: [
      "Password-protected PDFs need to be unlocked first with Unlock PDF.",
      "To merge only some pages, or mix pages from different files, use Organize PDF instead.",
    ],
    faq: [
      ["Is there a limit on how many PDFs I can merge?", "There is no fixed limit. Very large merges are limited only by your device's memory, because the work happens in your browser."],
      ["Will merging reduce quality?", "No. The pages are copied into the new file as they are, so text stays selectable and images keep their original resolution."],
    ],
    related: ["organize-pdf", "split-pdf", "alternate-mix", "compress-pdf", "pdf-to-zip"],
  },
  "split-pdf": {
    title: "Split PDF Online – Extract Pages or Split by Page Range",
    description: "Split a PDF by page ranges, every N pages, or extract the pages you choose into a new file. Free online PDF splitter that runs in your browser.",
    intent: ["split pdf", "split pdf online", "extract pages from pdf", "separate pdf pages", "pdf splitter"],
    anchor: "Split a PDF into parts",
    howTo: "split a PDF",
    intro: "Break one PDF into several smaller files, or pull out just the pages you need. Choose between page ranges, a fixed number of pages per file, or a list of pages to extract.",
    steps: [
      "Choose the PDF you want to split.",
      "Pick how to split it: By ranges (for example 1-3, 4-10), Every N pages, or Extract pages.",
      "When extracting, decide whether the chosen pages go into one PDF or one file each.",
      "Press Split PDF; several files download together as a ZIP.",
    ],
    features: [
      "Three ways to split: ranges, every N pages, or a list of pages such as 2, 5, 7-9.",
      "Shows the total page count so ranges are easy to write.",
      "Each part keeps the original text, links and image quality.",
    ],
    uses: [
      "Send only the relevant chapter of a long report.",
      "Turn a 100-page scan into one file per 10-page document.",
      "Pull a single signed page out of a contract.",
    ],
    limits: ["To split at chapters, use Split by bookmarks; to keep parts under an upload limit, use Split by size."],
    faq: [
      ["How do I extract one page from a PDF?", "Choose Extract pages and type the page number, for example 4. Turn on “Put them in one PDF” if you list several pages and want them in a single file."],
    ],
    related: ["split-by-size", "split-by-bookmarks", "split-by-text", "organize-pdf", "merge-pdf"],
  },
  "organize-pdf": {
    title: "Organize PDF Pages – Reorder, Rotate, Delete & Add Pages",
    description: "Drag PDF pages into a new order, rotate or delete them, and add pages from other PDFs, all on one screen. Free page organizer that works in your browser.",
    intent: ["reorder pdf pages", "organize pdf", "rearrange pdf pages", "delete pages from pdf", "move pages in pdf"],
    anchor: "Reorder, rotate and delete PDF pages",
    howTo: "rearrange PDF pages",
    intro: "See every page of your PDF as a thumbnail, then drag pages into a new order, rotate or remove them, and add pages from other files before saving.",
    steps: [
      "Choose one or more PDFs; every page appears as a thumbnail.",
      "Drag thumbnails to reorder them, and use the buttons on a page to rotate or delete it.",
      "Use Add pages to bring in pages from another PDF, and Undo if you change your mind.",
      "Save the result as a new PDF.",
    ],
    features: [
      "Drag-and-drop page sorting with live thumbnails.",
      "Rotate or delete single pages, reverse the whole order, and undo any step.",
      "Combine pages from several PDFs into one document.",
    ],
    uses: [
      "Fix a scan where pages came out in the wrong order or upside down.",
      "Remove blank or duplicate pages before sending a document.",
      "Build one PDF out of selected pages from several files.",
    ],
    related: ["merge-pdf", "rotate-pdf", "split-pdf", "edit-pdf"],
  },
  "rotate-pdf": {
    title: "Rotate PDF Pages Online – Turn One Page or All Pages",
    description: "Rotate every page of a PDF, or only the pages you list, by 90° or 180°, and save it permanently. Works on several PDFs at once, free and in your browser.",
    intent: ["rotate pdf", "rotate pdf pages", "rotate pdf online", "turn pdf sideways", "rotate pdf and save"],
    anchor: "Rotate PDF pages",
    howTo: "rotate a PDF",
    intro: "Turn sideways or upside-down pages the right way up and save the change in the file, so the PDF opens correctly everywhere.",
    steps: ["Choose one or more PDFs.", "Pick the rotation: right 90°, 180° or left 90°.", "Leave Pages as “all”, or list the pages to rotate, such as 2, 4-6.", "Press Rotate PDF and download."],
    features: ["Rotate all pages or only selected ones.", "Process several PDFs in one go.", "The rotation is saved in the file, not just in your viewer."],
    uses: ["Fix landscape tables that were scanned in portrait.", "Correct pages a phone scanner saved upside down."],
    limits: ["To rotate individual pages by looking at them, Organize PDF shows thumbnails of every page."],
    related: ["organize-pdf", "flip-pdf", "split-in-half", "scan-to-pdf"],
  },
  "alternate-mix": {
    title: "Alternate & Mix PDF Pages – Interleave Two PDFs",
    description: "Interleave the pages of two or more PDFs: one page from each in turn. Ideal for combining separately scanned front and back sides. Free, in your browser.",
    intent: ["interleave pdf pages", "merge front and back scans", "alternate pages pdf", "collate pdf pages", "combine odd and even pages pdf"],
    anchor: "Interleave pages from two PDFs",
    howTo: "interleave PDF pages",
    intro: "Take one page from each PDF in turn to build a single document. The usual reason: a scanner without duplex produced one file of front sides and another of back sides.",
    steps: [
      "Choose two or more PDFs and put them in order (fronts first).",
      "Turn on “Reverse the second file” if the backs were scanned last page first.",
      "Press Mix pages and download the interleaved PDF.",
    ],
    features: ["Mixes any number of files, one page from each in turn.", "Optional reverse order for the second file, for flipped scan stacks.", "Pages are copied without quality loss."],
    uses: ["Rebuild a double-sided document from two single-sided scans.", "Alternate question and answer pages from two files."],
    related: ["merge-pdf", "organize-pdf", "scan-to-pdf"],
  },
  "pages-per-sheet": {
    title: "Pages Per Sheet – Print 2, 4 or 16 PDF Pages on One Page",
    description: "Put 2, 4, 6, 9 or 16 PDF pages on each sheet (n-up) to save paper when printing handouts and notes. Choose A4, Letter, order and borders. Free.",
    intent: ["multiple pages per sheet pdf", "n-up pdf", "print 2 pages per sheet pdf", "4 pages per page pdf", "pdf handout"],
    anchor: "Put several PDF pages on one sheet",
    howTo: "print several PDF pages on one sheet",
    intro: "Shrink several pages onto each sheet of paper, the way printer “pages per sheet” settings do, but saved as a PDF you can share or print anywhere.",
    steps: ["Choose a PDF.", "Pick how many pages per sheet: 2, 4, 6, 9 or 16.", "Choose the sheet size (A4, Letter or the original size), the reading order, and whether to draw a thin border.", "Press Combine pages and download."],
    features: ["2, 4, 6, 9 or 16 pages per sheet.", "Across-then-down or down-then-across order.", "Optional border around each page."],
    uses: ["Print lecture slides as compact handouts.", "Save paper when proofreading a long document."],
    related: ["merge-pdf", "split-in-half", "page-numbers"],
  },
  "flip-pdf": {
    title: "Flip PDF – Mirror PDF Pages Horizontally or Vertically",
    description: "Mirror the pages of a PDF left to right, top to bottom, or both. Useful for iron-on transfers, light-box tracing and mirrored scans. Free and private.",
    intent: ["flip pdf", "mirror pdf", "mirror pdf for printing", "flip pdf horizontally", "reverse pdf image"],
    anchor: "Mirror PDF pages",
    howTo: "mirror a PDF",
    intro: "Create a mirror image of each page. Unlike rotating, flipping reverses the page, which is what transfer paper and some printers need.",
    steps: ["Choose one or more PDFs.", "Pick Left ↔ right, Top ↕ bottom, or Both.", "Press Flip PDF and download."],
    features: ["Horizontal, vertical or both.", "Keeps vector text and graphics sharp."],
    uses: ["Print iron-on transfers and T-shirt designs.", "Fix scans that came out mirrored."],
    limits: ["To turn pages without mirroring them, use Rotate PDF."],
    related: ["rotate-pdf", "organize-pdf"],
  },
  "split-in-half": {
    title: "Split PDF Pages in Half – Separate Two-Page Book Scans",
    description: "Cut every PDF page down the middle (or across) to turn two-page book spreads into single pages. Supports right-to-left books. Free, in your browser.",
    intent: ["split pdf page in half", "split scanned book pages", "cut pdf page in two", "separate two pages in one pdf page", "split double page pdf"],
    anchor: "Cut PDF pages in half",
    howTo: "split PDF pages in half",
    intro: "When a book or booklet is scanned two pages at a time, each PDF page holds a spread. This tool cuts every page into two so the document reads one page at a time.",
    steps: ["Choose the scanned PDF.", "Choose to cut down the middle or across the middle.", "For Arabic, Hebrew or Urdu books, turn on “Right half first”.", "Press Split pages in half and download."],
    features: ["Vertical or horizontal cut.", "Right-to-left reading order for RTL books.", "Text in the original stays selectable."],
    uses: ["Make a scanned book readable on a phone or e-reader.", "Separate A3 scans into A4 pages."],
    related: ["crop-pdf", "ocr-pdf", "organize-pdf", "pages-per-sheet"],
  },
  "split-by-size": {
    title: "Split PDF by File Size – Keep Every Part Under a Limit",
    description: "Break a large PDF into parts that are each under a size you choose, like 5 MB or 10 MB, for email attachments and upload portals. Free and private.",
    intent: ["split pdf by size", "split large pdf", "split pdf into 5mb parts", "pdf too large to upload", "split pdf for email"],
    anchor: "Split a large PDF by file size",
    howTo: "split a PDF by file size",
    intro: "Set the largest size allowed, such as 5 MB, and get as many parts as needed, each within that limit and in the original page order.",
    steps: ["Choose a PDF.", "Enter the largest size each part may be, in MB.", "Press Split by size; the parts download as a ZIP."],
    features: ["Any limit from 0.2 MB upwards.", "Parts keep the original page order and quality."],
    uses: ["Send a large document over email in several messages.", "Upload to court, tax or government portals with a per-file limit."],
    limits: ["A single page larger than the limit can't be split further; compress the PDF first if that happens."],
    related: ["compress-pdf", "gst-filing-prep", "split-pdf"],
  },
  "split-by-bookmarks": {
    title: "Split PDF by Bookmarks – One File per Chapter",
    description: "Turn each bookmarked chapter or section of a PDF into its own file, named after the bookmark. Free online tool that runs in your browser.",
    intent: ["split pdf by bookmarks", "split pdf by chapter", "extract chapters from pdf", "split pdf outline"],
    anchor: "Split a PDF into chapters",
    howTo: "split a PDF by bookmarks",
    intro: "If your PDF has bookmarks (the outline you see in a PDF reader's sidebar), each top-level bookmark becomes a separate PDF.",
    steps: ["Choose a PDF that has bookmarks.", "Check the list of sections that will become files.", "Press Split by bookmarks and download the ZIP."],
    features: ["Files are named after their bookmarks.", "Splits exactly where each section starts."],
    uses: ["Split an e-book or manual into chapters.", "Separate the documents bundled in a court or tender file."],
    limits: ["Only works when the PDF contains bookmarks; otherwise use Split PDF or Split by text."],
    related: ["split-pdf", "split-by-text", "split-by-size"],
  },
  "split-by-text": {
    title: "Split PDF by Text – Start a New File at a Keyword",
    description: "Split a PDF every time a page contains a phrase such as “Invoice No.”, to separate batches of invoices, statements or forms. Free, private, in your browser.",
    intent: ["split pdf by text", "split pdf by keyword", "split invoices pdf", "separate pdf by content"],
    anchor: "Split a PDF wherever a phrase appears",
    howTo: "split a PDF by text",
    intro: "Large exports often contain many documents in one PDF. Enter a phrase that appears on the first page of each one, and every match starts a new file.",
    steps: ["Choose the PDF.", "Type the phrase that starts each document, for example “Invoice No.”.", "Press Split by text and download the ZIP."],
    features: ["Finds the phrase in the PDF's text on every page.", "Pages before the first match are kept as their own file."],
    uses: ["Split a month of invoices into one PDF per invoice.", "Separate payslips or statements exported as one file."],
    limits: ["Needs selectable text; run OCR PDF first on scanned batches."],
    related: ["split-by-bookmarks", "split-pdf", "ocr-pdf"],
  },
  "pdf-to-zip": {
    title: "PDF to ZIP – Bundle Several PDFs into One ZIP File",
    description: "Put several PDF files into a single compressed ZIP archive with a name you choose, ready to email or upload. Free, and it never leaves your browser.",
    intent: ["pdf to zip", "zip pdf files", "compress pdfs into zip", "bundle pdf files"],
    anchor: "Bundle PDFs into a ZIP file",
    howTo: "put PDFs in a ZIP file",
    intro: "Package many PDFs into one ZIP file so they travel together as a single attachment or upload, each file unchanged inside.",
    steps: ["Choose the PDFs to bundle.", "Give the ZIP file a name.", "Press Create ZIP and download it."],
    features: ["Any number of PDFs in one archive.", "Files are stored unchanged inside the ZIP."],
    uses: ["Send a set of documents as one email attachment.", "Upload a folder of PDFs where only one file is allowed."],
    limits: ["ZIP saves little space on PDFs, which are already compressed. To make files smaller, use Compress PDF."],
    related: ["merge-pdf", "compress-pdf"],
  },
};
