import type { ToolSeo } from "./types";

const AI_NOTE = "The text is read from the PDF on your device; only that text is sent to our AI provider to produce the result, and nothing is stored.";

export const SECURITY: Record<string, ToolSeo> = {
  "protect-pdf": {
    title: "Password Protect PDF – Encrypt a PDF with AES-256",
    description: "Add a password to a PDF with AES-256 encryption, and choose whether printing, copying and editing are allowed. Free, and the file never leaves your browser.",
    intent: ["password protect pdf", "protect pdf", "encrypt pdf", "lock pdf with password", "add password to pdf"],
    anchor: "Password-protect a PDF",
    howTo: "password-protect a PDF",
    intro: "Encrypt a PDF so it can only be opened with the password you set. Optionally block printing, copying or editing for people who do open it.",
    steps: ["Choose one or more PDFs.", "Type a password and repeat it.", "Choose whether to allow printing, copying text and editing.", "Press Protect PDF and download."],
    features: ["AES-256 encryption, the strongest standard PDF encryption.", "Separate permissions for printing, copying and editing.", "Encryption happens on your device, so the password and file are never sent anywhere."],
    uses: ["Email payslips, statements or medical reports safely.", "Share a contract that only the recipient should open."],
    limits: ["If you forget the password, the PDF can't be recovered. Keep it somewhere safe.", "Send the password through a different channel than the file."],
    faq: [["How secure is a password-protected PDF?", "With AES-256 and a long, unique password, the content can't practically be opened without the password. Short or common passwords can be guessed, so use a strong one."]],
    related: ["unlock-pdf", "redact-pdf", "remove-restrictions", "watermark-pdf"],
  },
  "unlock-pdf": {
    title: "Unlock PDF – Remove a PDF Password You Know",
    description: "Remove the open password from a PDF you have the password for, and save an unlocked copy that opens without it. Free and private, in your browser.",
    intent: ["unlock pdf", "remove password from pdf", "pdf password remover", "decrypt pdf"],
    anchor: "Remove a PDF password",
    howTo: "remove a password from a PDF",
    intro: "Tired of typing the password every time you open your own statement? Enter it once and save a copy without encryption.",
    steps: ["Choose the protected PDF.", "Enter its current password.", "Press Unlock PDF and download the unlocked copy."],
    features: ["Removes the open password and permissions.", "Saves an ordinary PDF that every tool and reader can open.", "Decryption happens on your device."],
    uses: ["Remove the password from bank and credit card statements before archiving them.", "Unlock a PDF so other tools can merge or compress it."],
    limits: ["You need the correct password: this tool doesn't crack or guess passwords."],
    related: ["protect-pdf", "remove-restrictions", "merge-pdf", "compress-pdf"],
  },
  "redact-pdf": {
    title: "Redact PDF Online – Permanently Remove Sensitive Text",
    description: "Find words, names or numbers in a PDF and remove them for good: the text is deleted from the file and covered with a black box. Free, in your browser.",
    intent: ["redact pdf", "redact pdf online free", "black out text in pdf", "remove sensitive information from pdf"],
    anchor: "Redact text in a PDF",
    howTo: "redact a PDF",
    intro: "Real redaction deletes the text underneath, so it can't be copied, searched or recovered. A black box drawn on top is not enough, and this tool does both.",
    steps: ["Choose the PDF.", "Enter the words or numbers to remove, one per line.", "Choose whole words only and match case if needed.", "Press Redact and download; check the result before sharing."],
    features: ["Removes matching text from the file, not just visually.", "Search for several terms at once.", "Whole-word and case-sensitive matching."],
    uses: ["Hide account numbers before sharing a statement.", "Remove names from documents before publishing them."],
    limits: ["Text inside scanned images can't be found; run OCR PDF first or redact by hand in the PDF editor."],
    related: ["auto-redact-pii", "privacy-scanner", "edit-pdf", "protect-pdf"],
  },
  "remove-restrictions": {
    title: "Remove PDF Restrictions – Allow Printing, Copying & Editing",
    description: "Remove printing, copying and editing restrictions from a PDF you can already open, so you can print it, copy text or edit it. Free, in your browser.",
    intent: ["remove pdf restrictions", "pdf can't print", "enable copy in pdf", "remove pdf permissions password"],
    anchor: "Remove PDF printing and copying restrictions",
    howTo: "remove restrictions from a PDF",
    intro: "Some PDFs open without a password but block printing, copying or editing. This saves a copy without those permission flags.",
    steps: ["Choose the restricted PDF.", "Press Remove restrictions.", "Download the unrestricted copy."],
    features: ["Clears print, copy and edit restrictions.", "Content and layout stay unchanged."],
    uses: ["Print a form your organisation sent you that blocks printing.", "Copy a quote from a document you're allowed to use."],
    limits: ["PDFs that need a password to open must be unlocked with Unlock PDF instead.", "Only use this on documents you have the right to use this way."],
    related: ["unlock-pdf", "protect-pdf", "edit-pdf"],
  },
  "auto-redact-pii": {
    title: "Auto-Redact PII in PDF – Aadhaar, PAN, Card Numbers & Emails",
    description: "Automatically find and permanently remove Aadhaar, PAN, GSTIN, IFSC, IBAN, card numbers, emails and phone numbers from a PDF. Free, on your device.",
    intent: ["redact aadhaar number from pdf", "mask aadhaar in pdf", "remove personal information from pdf", "auto redact pdf", "hide pan number pdf"],
    anchor: "Auto-redact personal data in a PDF",
    howTo: "redact personal data automatically",
    intro: "Choose the kinds of personal data to remove and the tool finds every match with pattern checks (including checksums for Aadhaar and card numbers), then deletes them from the file.",
    steps: ["Choose the PDF.", "Tick the types to find: Aadhaar, PAN, card numbers, emails, phone numbers, GSTIN, IFSC or IBAN.", "Press Find & redact and review what was removed.", "Download the redacted PDF."],
    features: ["Eight kinds of personal and financial identifiers.", "Validates numbers to avoid false matches.", "Removes the text from the file, not just covering it."],
    uses: ["Mask Aadhaar numbers before submitting copies for KYC.", "Strip contact details from documents before publishing."],
    limits: ["Only selectable text is checked; scanned pages need OCR PDF first.", "Always look over the result: unusual formats may be missed."],
    related: ["redact-pdf", "privacy-scanner", "protect-pdf"],
  },
  "privacy-scanner": {
    title: "PDF Privacy Scanner – Find Personal & Hidden Data Before Sharing",
    description: "Scan a PDF for personal data, hidden properties, comments, attachments and scripts before you share it, and optionally get a cleaned copy. Free, on your device.",
    intent: ["check pdf for personal information", "pdf hidden data", "pdf privacy check", "remove hidden data from pdf"],
    anchor: "Check a PDF for hidden personal data",
    howTo: "check a PDF for private data",
    intro: "PDFs can carry more than you see: author names, edit history, comments, attachments and personal numbers. The scanner lists what it finds so you can decide before sending.",
    steps: ["Choose the PDF.", "Turn on “Also make a cleaned copy” if you want one.", "Press Scan for private data and read the report.", "Download the cleaned copy if you made one."],
    features: ["Detects identifiers like Aadhaar, PAN, card numbers, emails and phone numbers.", "Lists hidden properties and metadata.", "Optional cleaned copy with findings redacted and properties removed."],
    uses: ["Check a CV or contract before sending it to strangers.", "Audit documents before publishing them online."],
    related: ["auto-redact-pii", "edit-metadata", "redact-pdf"],
  },
  "file-fingerprint": {
    title: "File Hash Checker – SHA-256, SHA-1 & MD5 Checksums Online",
    description: "Calculate SHA-256, SHA-1 and MD5 hashes of any file to prove it hasn't changed, or compare two files. Free, and the file never leaves your device.",
    intent: ["sha256 checksum online", "file hash checker", "md5 checksum", "verify file integrity"],
    anchor: "Get a file's SHA-256 fingerprint",
    howTo: "check a file's hash",
    intro: "A hash is a short fingerprint of a file's exact contents. If even one byte changes, the fingerprint changes, which makes it a simple way to prove a document is untouched.",
    steps: ["Choose one or more files.", "Press Generate fingerprints.", "Copy the hashes, or compare them with a value you were given."],
    features: ["SHA-256, SHA-1 and MD5.", "Works with any file type.", "Computed on your device."],
    uses: ["Record the fingerprint of a signed contract or evidence file.", "Check a download against the checksum its publisher lists."],
    related: ["protect-pdf", "compare-pdf"],
  },
};

export const AI: Record<string, ToolSeo> = {
  "compare-pdf": {
    title: "Compare PDF Files – See Every Change Between Two Versions",
    description: "Compare two PDFs side by side: see added and removed text, or a visual overlay of changed areas on every page. Free, and both files stay in your browser.",
    intent: ["compare pdf", "compare two pdf files", "pdf diff", "find differences between pdfs"],
    anchor: "Compare two PDF versions",
    howTo: "compare two PDFs",
    intro: "Check what changed between two versions of a contract, drawing or report, either as a list of text changes or as pages with the differences highlighted in red.",
    steps: ["Choose the original PDF and the new version.", "Press Compare.", "Switch between Text changes and Visual to review the differences."],
    features: ["Text comparison with additions and deletions marked.", "Visual mode highlights changed areas on each page.", "Runs entirely in your browser, with no AI or upload."],
    uses: ["Check the edits in a contract the other side sent back.", "Spot changes between two revisions of a drawing or brochure."],
    limits: ["Text comparison needs selectable text; Visual mode works on scans too."],
    related: ["file-fingerprint", "summarize-pdf", "edit-pdf"],
  },
  "summarize-pdf": {
    title: "AI PDF Summarizer – Summarize Long PDFs in Seconds",
    description: "Get the key points of a long PDF in a short, medium or detailed summary. Free AI PDF summarizer, no sign-up, and your document isn't stored.",
    intent: ["summarize pdf", "ai pdf summarizer", "pdf summary generator", "summarize document"],
    anchor: "Summarize a PDF with AI",
    howTo: "summarize a PDF",
    intro: `Skim long reports, papers and policies faster with a summary of their main points. ${AI_NOTE}`,
    steps: ["Choose a PDF with selectable text.", "Pick the length: short, medium or long.", "Press Summarize, then copy or download the summary."],
    features: ["Short, medium or long summaries.", "Copy the summary or download it as a file."],
    uses: ["Decide whether a long report is worth reading in full.", "Get the gist of a research paper or policy."],
    limits: ["AI summaries can miss nuance or make mistakes; check important details in the document.", "Scanned PDFs need OCR PDF first."],
    related: ["chat-with-pdf", "translate-pdf", "pdf-to-audio"],
  },
  "translate-pdf": {
    title: "Translate PDF Online with AI – 20+ Languages",
    description: "Translate a whole PDF document into English, Hindi, Spanish, French, German, Arabic, Chinese and more. Free AI document translator, no sign-up.",
    intent: ["translate pdf", "translate pdf online", "pdf translator", "translate document to english", "translate pdf to hindi"],
    anchor: "Translate a PDF",
    howTo: "translate a PDF",
    intro: `Translate the text of an entire document into one of 21 languages, keeping its headings and paragraphs. ${AI_NOTE}`,
    steps: ["Choose a PDF with selectable text.", "Pick the language to translate into.", "Press Translate, then copy or download the translation."],
    features: ["21 languages including Hindi, Tamil, Telugu, Marathi, Bengali, Arabic, Chinese and Japanese.", "Keeps the document's structure of headings and paragraphs."],
    uses: ["Understand a contract or letter in a foreign language.", "Share a document with family or colleagues in their language."],
    limits: ["The output is text, not a re-laid-out copy of the original PDF.", "Machine translation can be wrong; get professional translation for legal use."],
    related: ["summarize-pdf", "chat-with-pdf", "pdf-to-word"],
  },
  "chat-with-pdf": {
    title: "Chat with PDF – Ask Questions and Get Answers with Page Numbers",
    description: "Ask questions about any PDF and get answers that cite the pages they come from. Free AI chat for contracts, papers and manuals, no sign-up.",
    intent: ["chat with pdf", "ask questions about pdf", "ai pdf reader", "pdf ai chat", "chatpdf alternative"],
    anchor: "Ask questions about a PDF",
    howTo: "chat with a PDF",
    intro: `Ask in your own words, like “What is the notice period?”, and get an answer with the page numbers to check it. ${AI_NOTE}`,
    steps: ["Choose a PDF with selectable text.", "Type a question or pick a suggested one.", "Read the answer and open the cited pages to check it; ask follow-up questions."],
    features: ["Answers cite the pages they rely on.", "Follow-up questions keep the conversation's context.", "Suggested starter questions."],
    uses: ["Find clauses in a long contract.", "Study from lecture notes and papers.", "Look up how-to answers in a product manual."],
    limits: ["AI can be wrong; use the page references to verify answers.", "Scanned PDFs need OCR PDF first."],
    related: ["summarize-pdf", "translate-pdf", "ocr-pdf", "pdf-to-audio"],
  },
  "pdf-to-audio": {
    title: "PDF to Audio – Read PDF Aloud Online with Highlighting",
    description: "Listen to any PDF read aloud with your device's voices, choose voice and speed, and follow the highlighted sentence. Free text-to-speech, no upload.",
    intent: ["pdf to audio", "read pdf aloud", "pdf text to speech", "listen to pdf"],
    anchor: "Listen to a PDF read aloud",
    howTo: "listen to a PDF",
    intro: "Turns a PDF into speech using the voices built into your device or browser. The current sentence is highlighted, and you can tap any sentence to jump there.",
    steps: ["Choose a PDF with selectable text.", "Pick a voice and speed.", "Press play; tap a sentence to jump to it."],
    features: ["Sentence highlighting as it reads.", "Any voice installed on your device, at adjustable speed.", "No AI and no upload: speech is made by your browser."],
    uses: ["Listen to articles and reports while commuting.", "Proofread your own writing by ear.", "Support for reading difficulties."],
    limits: ["Voice quality depends on your device; some browsers offer more natural voices than others.", "Scanned PDFs need OCR PDF first."],
    related: ["summarize-pdf", "translate-pdf", "extract-text"],
  },
};
